// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://easxexwcahngnaqankwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhc3hleHdjYWhuZ25hcWFua3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTA3NzYsImV4cCI6MjA2NTU2Njc3Nn0.SmqngtHuZUxNGUXT6iXieRlMdWzfFwPq5ZcbO8rr0mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);